name: "Microservices Linting"

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs: # list of things to do
  lint_service:
    name: Linting Microservice
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [dataretrieval, usermanagement]

    steps: # list of steps
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js and Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: services/${{ matrix.service }}

      - name: Lint Code
        run: npm run lint
        working-directory: services/${{ matrix.service }}
